### ISSUE TITLE
테스트 스키마 생성

### ISSUE THREAD

**Issue by dabeen-jung** [KOSA-MOJI/MOJI#10]
## 💼 작업 설명

BE 작업을 위한 임시 테이블을 생성합니다. 
테이블은 다이어리,페이지, 제공속지 이미지, 지도주소, 지도 추가 이미지 url 입니다.

## ✅ To-do

- [ ] 테이블 스키마 생성
- [ ] 테이블 외래키 관계 수정
- [ ] 임시 데이터 삽입
