### ISSUE TITLE
[FE] 다이어리 조회 및 작성 -  jsp 및 js 세션 적용

### ISSUE THREAD

**Issue by dabeen-jung** [KOSA-MOJI/MOJI#106]
## 💼 작업 설명

**다이어리 조회 및 작성**의 jsp와 js에 세션을 적용합니다.

## ✅ To-do

- [ ] diary-read.jsp 세션 설정
- [ ] diary-read.js 세션 연결
- [ ] diary-write.jsp 세션 설정
- [ ] diary-write.js 세션 연결
