### ISSUE TITLE
[BE] 기능 수정

### ISSUE THREAD

**Issue by cookooyas** [KOSA-MOJI/MOJI#118]
## 💼 작업 설명

전반적인 기능 수정 작업입니다.

## ✅ To-do

- [ ] 로그인 및 사용자 권한 수정
- [ ] 권한 기반 API 명세 재정의
- [ ] 반환 구조 정의 및 API 명세 정의
