### ISSUE TITLE
[FE] 다이어리 작성 화면 CSS 스타일링

### ISSUE THREAD

**Issue by cookooyas** [KOSA-MOJI/MOJI#131]
## 💼 작업 설명

다이어리 작성 시 컴포넌트에 CSS 요소 수정
기타 문제 사항 해결

## ✅ To-do

- [x] 다이어리 작성 - 이미지 추가 시, 버튼과 이미지 요소 겹침 문제 수정
- [x] 다이어리 작성 - 이미지 추가 시, 이미지 삭제 버튼의 가시성이 떨어지는 문제 수정
- [x] 다이어리 작성 - 이미지 추가 시, 이미지가 존재하지 않을 경우 버튼 비활성화
- [x] 다이어리 작성 - 일기 내용 작성 영역의 default문구를 place holder로 두게끔 정의
- [x] 다이어리 작성 - 일기 내용 작성 시, 줄 바꿈수가 화면 너비를 넘어갈 경우 스크롤바가 생기게끔 수정
