### ISSUE TITLE
MOJI 프로젝트 폴더 아키텍처 구성 및 테스트 코드 작성

### ISSUE THREAD

**Issue by cookooyas** [KOSA-MOJI/MOJI#3]
## 💼 작업 설명

전반적인 폴더 아키텍처 구성 및 MVC 패턴 테스트 코드 작성

## ✅ To-do

- [x] JSP/CSS/JS 관련 폴더 아키텍처 구성
- [x] Spring boot MVC 패턴 중심 폴더 아키텍처 구성
- [x] 테스트 코드 
- [x] JDK 21 버전 업데이트
