### ISSUE TITLE
[FE] 커뮤니티 페이지 스크랩 구현

### ISSUE THREAD

**Issue by dabeen-jung** [KOSA-MOJI/MOJI#42]
## 💼 작업 설명

커뮤니티 페이지의 스크랩을 적용하기 위해 jsp,css,js를 수정 및 추가합니다

## ✅ To-do

- [x] 스크랩 생성 버튼 
   - [x] js 동작 및 css 수정
- [x] 스크랩 삭제 버튼
   - [x] js 동작 및 css 수정
