### ISSUE TITLE
[BE] 커뮤니티 서비스 REST API 구현

### ISSUE THREAD

**Issue by cookooyas** [KOSA-MOJI/MOJI#49]
## 💼 작업 설명

커뮤니티 서비스 REST API 기능 (api/community/..) 개발
## ✅ To-do

- [x] 커뮤니티 서비스 내 페이지 조회 (Lazy Loading API) 기능 개발
    - [x] 커뮤니티 RestController 개발
    - [x] 커뮤니티 Service 개발 
    - [x] 커뮤니티 페이지 조회 관련 Entity, DTO 정의
    - [x] 커뮤니티 페이지 조회 관련 매퍼 정의
    - [ ] API 명세 등록
- [x] 커뮤니티 서비스 내 페이지 스크랩 기능 개발
    - [x] 커뮤니티 스크랩 기능 관련 컨트롤러 메서드 추가
    - [x] 커뮤니티 스크랩 기능 서비스 메서드 추가
    - [x] 커뮤니티 스크랩 기능 관련 Entity,DTO 정의
    - [x] 커뮤니티 스크랩 기능 관련 매퍼 정의
    - [ ] API 명세 등록
