### ISSUE TITLE
[FEAT]: 커뮤니티 조회 기능 프론트와 연동 

### ISSUE THREAD

**Issue by dabeen-jung** [KOSA-MOJI/MOJI#54]
## 💼 작업 설명

lazy load 공개된 페이지 목록 조회 api 연결 및 이미지 클릭시 
해당 단건 페이지 조회 api를 FE와 연동시킵니다. 

## ✅ To-do

- [x] 공개된 페이지 목록조회 api 연동
- [ ] lazy load 연결
  - [ ] js - array 스크랩 여부, page_id 담기
- [ ] 이미지 클릭시 단건 페이지 조회 api 연동
