### ISSUE TITLE
[BE] 다이어리, 커뮤니티 관련 REST API 기능 수정 및 기능 추가

### ISSUE THREAD

**Issue by cookooyas** [KOSA-MOJI/MOJI#57]
## ✅ To-do

- [x] 페이지 생성 로직 내 추가되거나 변경된 속성(글자 크기, 글자 색, 텍스트 정렬, 날씨) 반영
    - [x] 글자 크기, 글자 색, 텍스트 정렬 속성 엔티티, 매퍼 추가
    - [x] 날씨 속성의 변화 (텍스트->이미지 URL)로 인한 SQL 변경 

- [x] 다이어리 조회 시, 북마크 관계 매핑
    - [x]  관련 정보로 엔티티 수정

- [x] 페이지 작성 시 템플릿 조회 관련 API기능 구현
    - [x] 새로운 기능을 위해 컨트롤러, 서비스, 매퍼, 쿼리 추가
    - [x] API 기능명세서 작성
  
- [x] 페이지 작성 시 이미지 S3 사전 업로드 관련 API기능 구현
    - [x] 이미지 사전 등록 API 구현
    - [x] 사전 등록 이미지 삭제 API 구현
    - [x] API 기능명세서 작성

- [x] 페이지 작성 및 삭제 관련 API기능 구현
    - [x] 새로운 기능을 위해 컨트롤러, 서비스, DTO, 매퍼, 쿼리 추가
    - [x] 추가, 삭제 기능 구현
    - [x] API 기능명세서 작성

- [x] 페이지 조회 시, 공개 여부 업데이트 기능 추가
    - [x] 새로운 업데이트 기능을 위해 컨트롤러, 서비스, 매퍼, 쿼리 추가
    - [x] API 기능명세서 작성

- [x] 커뮤니티 서비스 내 스크랩 등록, 삭제 로직 수정

- [ ] 기타 리팩토링 및 ResponseEntity를 활용한 반환 오브젝트 통일
