### ISSUE TITLE
[FE] 커뮤니티 조회 상단 단건 페이지 조회 기능 추가

### ISSUE THREAD

**Issue by cookooyas** [KOSA-MOJI/MOJI#62]
## 💼 작업 설명

커뮤니티 조회 서비스에서 상단 단건 페이지 조회 기능 추가

## ✅ To-do

- [x] 상단 단건 페이지 조회를 위한 REST API 호출 및 가공
- [x] 요구사항에 맞는 좌측, 우측 요소 구현
- [x] 페이지 스크랩 관련 REST API 연결 및 제작
