### ISSUE TITLE
[FE] 다이어리 페이지 조회 기능 추가

### ISSUE THREAD

**Issue by cookooyas** [KOSA-MOJI/MOJI#68]
## 💼 작업 설명

다이어리 서비스 내 페이지 조회 시 DB에 저장된 정보 반영
공개 여부 설정 기능 추가
## ✅ To-do

- [x] 템플릿 이미지 반영
- [x] 반영 템플릿 기준 페이지 애니메이션 효과 수정
- [x] 글자 색, 글자 크기, 글자 정렬 반영
- [x] 공개 여부 설정 기능 추가
