### ISSUE TITLE
[FE] 필터 모달 CSS,js 추가 및 수정

### ISSUE THREAD

**Issue by dabeen-jung** [KOSA-MOJI/MOJI#74]
## 💼 작업 설명

필터 모달의 UI를 수정하여 모달에서 몇키로미터를 설정했는지 보여주기

## ✅ To-do

- [x] 모달을 킬 때 ->  현재까지 설정되어 있었던 'radius'(반경)을 표시
- [x] 모달에서 range 변경 때마다, km 표시
- [x] 커뮤니티에서 사용한 login-modal.css와 layout.css 중복 수정
