### ISSUE TITLE
[FE] 커뮤니티 페이지 조회 CSS 수정

### ISSUE THREAD

**Issue by dabeen-jung** [KOSA-MOJI/MOJI#80]
## ✅ To-do

- [ ] 대체이미지 찾아서 변경
- [ ] 커뮤니티 이미지 갤러리 - 이미지가 길이에 따라 안 깨지도록 조정
- [ ] 커뮤니티 페이지 js쪽 css 수정
