### ISSUE TITLE
[BE] 스크랩, 일기 기반 지도 조회 서비스 REST API 구현

### ISSUE THREAD

**Issue by cookooyas** [KOSA-MOJI/MOJI#98]
## 💼 작업 설명

스크랩, 본인의 다이어리 기반으로 지도 상에 데이트 스팟을 조회하는 서비스 (이하 맵)
맵 서비스 관련 REST API 구현
## ✅ To-do

- [x] REST API 설계 (내가 스크랩한 정보 가져오기, 연인이 스크랩한 정보 가져오기, 커플이 등록한 위치 가져오기)
- [x] REST API 컨트롤러/서비스 구현
- [x] 관련 매퍼 설계 및 서비스 로직 구현
- [x] 기능 명세서 등록
